### ISSUE TITLE
Example2

### ISSUE THREAD

**Issue by YididiyaM** [YididiyaM/HYF-Javascript#2]
Example 2 as a test

**Comment by YididiyaM** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Yididiya](https://trello.com/c/0W3d7jd7/61-yididiya)

**Comment by hosseinz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hossein](https://trello.com/c/bjD0frnm/67-hossein)
